const ProductoMayor = [
  {
    id: 1,
    title: "Dos Corazones Felfort Bocadito Chocolate Relleno Caja X20 Un",
    img: "../../public/2corazones.jpg",
    descripcion: "Lorem ipsum dolor sit amet consectetur Lorem ipsum dolor sit amet consecteturLo",
    precioMayor: 20700,
    precioUni: 1190,
    categoria: "chocolate",
    subCategoria: "bocados",
    off: false,
  },
  {
    id: 2,
    title: "Bizcochos 9 De Oro Clasicas Galletitas",
    img: "../../public/9deOroClasica.jpg",
    descripcion: "",
    precioMayor: 560,
    precioUni: 590,
    categoria: "galletitas",
    subCategoria: "saladas",
    off: false,
  },
  {
    id: 3,
    title: "Bizcochos 9 De Oro Agridulces Galletitas",
    img: "../../public/9deOroDulce.jpg",
    descripcion: "",
    precioMayor: 560,
    precioUni: 590,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 4,
    title: "Bizcochos 9 De Oro Light Galletitas",
    img: "../../public/9deOroLight.jpg",
    descripcion: "",
    precioMayor: 560,
    precioUni: 590,
    categoria: "galletitas",
    subCategoria: "",
    off: false,
  },
  {
    id: 5,
    title: "Alfajor Cofler Block 60g ",
    img: "../../public/AlfajorBLock.jpg",
    descripcion: "",
    precioMayor: 810,
    precioUni: 900,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 6,
    title: "Alfajor Bagley Blanco Triple",
    img: "../../public/alfajorBN.jpg",
    descripcion: "",
    precioMayor: 800,
    precioUni: 842,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 7,
    title: "Alfajor Bagley Negro Triple",
    img: "../../public/alfajorNB.jpg",
    descripcion: "",
    precioMayor: 800,
    precioUni: 842,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 8,
    title: "Alfajor triple Bon O Bon Arcor 60g",
    img: "../../public/alfajorBonobon.jpg",
    descripcion: "",
    precioMayor: 800,
    precioUni: 842,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 9,
    title: "Alfajor Guaymallen Simple (NEGRO/BLANCO)",
    img: "../../public/alfajorGuaymallen.jpg",
    descripcion: "la caja de ser de chocolate negro, blanco o mitad y mitad",
    precioMayor: 6992.2,
    precioUni: 179,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 10,
    title: "Alfajor Guaymallen Triple (NEGRO/BLANCO)",
    img: "../../public/alfajorGuaymallenTriple.jpg",
    descripcion: "la caja de ser de chocolate negro, blanco o mitad y mitad ",
    precioMayor: 7083.2,
    precioUni: 298.5,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 11,
    title: "Alfajor Jorgelin Triple (BLANCO/NEGRO) ",
    img: "../../public/alfajorJorgelin.jpg",
    descripcion: " precio por mayor +16un, precio por menor +6  ",
    precioMayor: 688.5,
    precioUni: 692,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 12,
    title: "Alfajor Jorgito Triple (NEGRO/BLANCO)",
    img: "../../public/alfajorJorgito.jpg",
    descripcion: "precio por mayor +16un, precio por menor +6  ",
    precioMayor: 111,
    precioUni: 987,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 13,
    title: "Alfajor Tofi Triple (NEGRO/BLANCO)",
    img: "../../public/alfajorTofi.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 14,
    title: "Alfajor Mini Fantoche * 6 UNI.",
    img: "../../public/alfaMiniChoco.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 15,
    title: "Bon o Bon Aguila - Bocaditos *18 UNI. ",
    img: "../../public/bombBonobon.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "bocados",
    off: false,
  },
  {
    id: 16,
    title: "Budin Don Satur con chip de Chocolate 190g",
    img: "../../public/BudinDonSaturChip.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "budin",
    subCategoria: "",
    off: false,
  },
  {
    id: 17,
    title: "Budin Don Satur Frutal 190g",
    img: "../../public/BudinDonSAturFrutal.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "budin",
    subCategoria: "",
    off: false,
  },
  {
    id: 18,
    title: "Budin Don Satur Marmolado 190g",
    img: "../../public/budinDonSaturMarmolado.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "budin",
    subCategoria: "",
    off: false,
  },
  {
    id: 19,
    title: "Bull Dog Frutilla Acida",
    img: "../../public/bullDogFrutillaAcida.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "mentitas",
    off: false,
  },
  {
    id: 20,
    title: "Bull Dog MIX mandarina/uva",
    img: "../../public/bullDogMIXmandUva.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "mentitas",
    off: false,
  },
  {
    id: 21,
    title: "Bull Dog MIX sandia/manzana",
    img: "../../public/bullDogMIXsaMzana.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "mentitas",
    off: false,
  },
  {
    id: 22,
    title: "Bull Dog Manzana Acida",
    img: "../../public/bulldogMzaAcida.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "mentitas",
    off: false,
  },
  {
    id: 23,
    title: "Bull Dog Sandia Acida ",
    img: "../../public/bullDogSandiaAcida.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "mentitas",
    off: false,
  },
  {
    id: 24,
    title: "Bull DOg Uva Acida",
    img: "../../public/bullDogUvaAcida.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "mentitas",
    off: false,
  },
  {
    id: 25,
    title: "Cafe instantanio Arlistan 50g",
    img: "../../public/cafeArlistan50g.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "cafe",
    subCategoria: "cafe instantanio",
    off: false,
  },
  {
    id: 26,
    title: "Cafe instantanio Arlistan 100g",
    img: "../../public/cafeArlistan100g.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "cafe",
    subCategoria: "cafe instantanio",
    off: false,
  },
  {
    id: 27,
    title: "Cafe LA MORENITA saquitos * 20 UNI",
    img: "../../public/cafeLAMorenitaSAQ.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "cafe",
    subCategoria: "cafe saquitos",
    off: false,
  },
  {
    id: 28,
    title: "Cafe La Virginia 50g",
    img: "../../public/cafeLaVirginia50g.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "cafe",
    subCategoria: "",
    off: false,
  },
  {
    id: 29,
    title: "Cafe instantanio LA VIRGINIA ",
    img: "../../public/cafeLaVirginiaInst100g.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "cafe",
    subCategoria: "cafe instantanio",
    off: false,
  },
  {
    id: 30,
    title: "Campari 750cc",
    img: "../../public/campari.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "bebida Alcoholica",
    subCategoria: "",
    off: false,
  },
  {
    id: 31,
    title: "Capuchino LA VIRGINIA 125g",
    img: "../../public/capuchinoLaVirginia125g.jpg",
    descripcion: " ",
    precioMayor: 123,
    precioUni: 987,
    categoria: "cafe",
    subCategoria: "capuchino",
    off: false,
  },
  {
    id: 32,
    title: "Butter Toffos Bolsa de caramelo de DDL con Choco",
    img: "../../public/carameloChoco.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 33,
    title: "Caramelo Menta Cristal Arcor",
    img: "../../public/carameloMentaCristal.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 34,
    title: "Caramelo Menta Rosa",
    img: "../../public/carameloMentaRosa.jpg",
    descripcion: " ",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 35,
    title: "Bolsa Caramelo Miel ",
    img: "../../public/carameloMiel.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 36,
    title: "Bolsa Caramelo Palito de la Celva",
    img: "../../public/carameloPalitodelaCelva.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 37,
    title: "CBSe Yerba 1kg ",
    img: "../../public/cbse1kg.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "yerba",
    subCategoria: "",
    off: false,
  },
  {
    id: 38,
    title: "CBSe Yerba 500g",
    img: "../../public/CBSe500g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "yerba",
    subCategoria: "",
    off: false,
  },
  {
    id: 39,
    title: "CBSe Naranja Yerba 500g ",
    img: "../../public/cbseNja500g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "yerba",
    subCategoria: "",
    off: false,
  },
  {
    id: 40,
    title: "CBSe  Pomelo Yerba",
    img: "../../public/cbsepomelo500g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "Yerba",
    subCategoria: "",
    off: false,
  },
  {
    id: 41,
    title: "Barra cereal Frutilla con CHOCO ",
    img: "../../public/cerealFortfrutilla.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "Barra de cereal",
    subCategoria: "",
    off: false,
  },
  {
    id: 42,
    title: "Barra cereal Fort Frutilla ",
    img: "../../public/cerealFortFrutillaClasico.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "Barra de cereal",
    subCategoria: "",
    off: false,
  },
  {
    id: 43,
    title: "Barra cereal Fort Granola",
    img: "../../public/cerealFortGranola.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "Barra de cereal",
    subCategoria: "",
    off: false,
  },
  {
    id: 44,
    title: "Barra cereal MIX ",
    img: "../../public/cerealmix.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "Barra de cereal",
    subCategoria: "",
    off: false,
  },
  {
    id: 45,
    title: "Barra ceereal Mix CHOCO",
    img: "../../public/cerealmixchoco.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "Barra de cereal",
    subCategoria: "",
    off: false,
  },
  {
    id: 46,
    title: "Barra cerel Fort Fruta",
    img: "../../public/cerealMIXfruta.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "Barra de cereal",
    subCategoria: "",
    off: false,
  },
  {
    id: 47,
    title: "Chicle TopLine / 5 diferente sabores",
    img: "../../public/chicletoplineViolet.jpg",
    descripcion:
      "La compra minima de 5 por sabor, cuenta como oferta llevando surtido de 5 en 5",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chicle",
    subCategoria: "",
    off: false,
  },
  {
    id: 48,
    title: "ChocoArroz (Clasico, Blanco, FRutilla)",
    img: "../../public/chocoArrozClasico.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 49,
    title: "Daqui Chocolate 70g",
    img: "../../public/chocodaqui70g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 50,
    title: "Daqui Chocolate 120g ",
    img: "../../public/chocoDaqui120g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 51,
    title: "Chocolatito GEORGALO 25g ",
    img: "../../public/chocogeo25g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 52,
    title: "Hamlet chocolate ",
    img: "../../public/chocoHamlet.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 53,
    title: " Kinder Chocolate 43g ",
    img: "../../public/chocoKinder43g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 54,
    title: "Block Chocolate 110g ",
    img: "../../public/chocolateBlock110g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 55,
    title: "Block Chocolate 170g",
    img: "../../public/chocolateBlock170g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 56,
    title: "Block Chocolate 300g",
    img: "../../public/chocolateBlock300g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 57,
    title: "Chocolate Cofler (BLANCO/NEGRO) 100g",
    img: "../../public/chocolateCofler100g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 58,
    title: "Chocolate Cofler (BLANCO/NEGRO) 27g",
    img: "../../public/chocolateCofler27g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 59,
    title: "Chocolate Cofler (BLANCO/NEGRO) 55g",
    img: "../../public/chocolateCofler55g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 60,
    title: "Tofi Chocolate 28g ",
    img: "../../public/chocolatetofi28g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 61,
    title: "Chocolinas 170g",
    img: "../../public/chocolinas170g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 62,
    title: "Tokke Chocolate 72g",
    img: "../../public/chocoTOkke72g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 63,
    title: "Bolsa POP Chupetin Azul 24 UNI. ",
    img: "../../public/chupetinAzul.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chupetin",
    subCategoria: "",
    off: false,
  },
  {
    id: 64,
    title: "Bolsa caramelo POP 50 uni.",
    img: "../../public/chupetinPOPfruta50.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chupetin",
    subCategoria: "",
    off: false,
  },
  {
    id: 65,
    title: "Bolsa Chupetin POP rojo 24 UNI",
    img: "../../public/chupetinrojo24.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chupetin",
    subCategoria: "",
    off: false,
  },
  {
    id: 66,
    title: "Don Satur Dulce ",
    img: "../../public/donsaturdulce.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 67,
    title: "Don Satur Negritas",
    img: "../../public/donSaturNegro.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 68,
    title: "Don Satur Saladas",
    img: "../../public/DONSATURSALADO.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "saladas",
    off: false,
  },
  {
    id: 69,
    title: "Don Satur 100% vegetal",
    img: "../../public/DONSATURveg.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "saladas",
    off: false,
  },
  {
    id: 70,
    title: "Duracel AA 12 - Pilas ",
    img: "../../public/duracelaa12.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "pilas",
    subCategoria: "",
    off: false,
  },
  {
    id: 71,
    title: "Duracel AAA 14 - Pilas",
    img: "../../public/duracelAAA14.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "pilas",
    subCategoria: "",
    off: false,
  },
  {
    id: 72,
    title: "Endulcorante Tuy 50 sobrecitos",
    img: "../../public/endulcoranteTuy50.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "endulsante",
    subCategoria: "",
    off: false,
  },
  {
    id: 73,
    title: "Endulcorante Tuy 200cc",
    img: "../../public/endulcoranteTuy200cc.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "endulsante",
    subCategoria: "",
    off: false,
  },
  {
    id: 74,
    title: "Alfajor Fantoche Triple (BLANCO/NEGRO)",
    img: "../../public/fantocheTriple.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 75,
    title: "Ferrero 4 unidades",
    img: "../../public/ferrero4uni.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "bocados",
    off: false,
  },
  {
    id: 76,
    title: "Flynn Paff (clasico, uva, vainilla/frutillas)",
    img: "../../public/flynnpaff.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 77,
    title: "Flynn Paff XXL",
    img: "../../public/flynnpaffXXL.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 78,
    title: "Full Mani Chocolate 100g ",
    img: "../../public/fullmani100g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 79,
    title: "Full Mani Chocolate 160g",
    img: "../../public/fullmani160g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "",
    off: false,
  },
  {
    id: 80,
    title: "Amor Galletita 110g",
    img: "../../public/galleAmor110g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 81,
    title: "Galletitas Cofler Cookies/ Bon o Bon 105g",
    img: "../../public/galleCoflerCookiesBoB105g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 82,
    title: "Galletita Cofler Relleno de chocolate 85g",
    img: "../../public/galleCoflerRellChoco85g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 83,
    title: "Galletitas Cookies Bañadas 132g",
    img: "../../public/gallecookiesBañada132g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 84,
    title: "Criollitas - Galletitas * 3",
    img: "../../public/galleCriollitas3.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "galletitas de agua",
    off: false,
  },
  {
    id: 85,
    title: "Criollitas - Galletitas 100g",
    img: "../../public/gallecriollitas100g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "galletitas de agua",
    off: false,
  },
  {
    id: 86,
    title: "Donus Bonafide 78g",
    img: "../../public/galleDonus78g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 87,
    title: "Fauna Galletitas 150g",
    img: "../../public/galleFauna150g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 88,
    title: "Fauna Galletitas 400g",
    img: "../../public/galleFauna400g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 89,
    title: "Hogareña Galletitas 167g",
    img: "../../public/galleHogareña167g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "galletitas de agua",
    off: false,
  },
  {
    id: 90,
    title: "Hogareña Galletitas 189g",
    img: "../../public/galleHogareñaMix189g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "galletitas de agua",
    off: false,
  },
  {
    id: 91,
    title: "Hojaldre Galletitas 150g",
    img: "../../public/galleHojaldre150g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 92,
    title: "Holjamar Trriang 150g",
    img: "../../public/gallehojalmarTriang150g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 93,
    title: "Mana de chocolate Galletitas ",
    img: "../../public/galleManaChoco.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 94,
    title: "Mana de choco RELL vainilla",
    img: "../../public/galleManaChocoVainilla.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 95,
    title: "Galletita Media Tarde * 3",
    img: "../../public/galleMediaTArde.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "galletitas de agua",
    off: false,
  },
  {
    id: 96,
    title: "Palmerita Galletita Veggie",
    img: "../../public/gallepalmeritaVeg.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 97,
    title: "Paseo Galletitas 300g",
    img: "../../public/gallepaseo300g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "galletitas de agua",
    off: false,
  },
  {
    id: 98,
    title: "Paseo con Semola Galletita 300g",
    img: "../../public/gallepaseoSemola300g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "galletitas de agua",
    off: false,
  },
  {
    id: 99,
    title: "Galletias con Rocklets",
    img: "../../public/galleRocklets.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 100,
    title: "Sonrisas Galletitas ",
    img: "../../public/gallesonrisas.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 101,
    title: "Diversion Galletitas Surtidas",
    img: "../../public/gallesurtidodiversion.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 102,
    title: "Galletita BLOCK 124g",
    img: "../../public/galletitaBlock124g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 103,
    title: "Galletita Cofler/Bon o Bon 85g",
    img: "../../public/galletitaCoflerYBoB85g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 104,
    title: "Vainillita Galletita",
    img: "../../public/galleVainillita.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 105,
    title: "Vocacion Galletitas",
    img: "../../public/galleVocacion.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 106,
    title: "Gomitas de Frutilla Billiken 800g",
    img: "../../public/gomaBFruta800g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 107,
    title: "Gomitas TUTTI 800g",
    img: "../../public/gomaBtutti800g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 108,
    title: "Gomitas Frutilla Acida 500g- Mogul",
    img: "../../public/gomaMfrutillaacida500g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 109,
    title: "Gomitas Moras 500g - Mogul",
    img: "../../public/gomaMMoras500g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 110,
    title: "Gomitas ositos Acidas 50g - Mogul",
    img: "../../public/gomaMOsoAcido50g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 111,
    title: "Gomitas Tubitos 70g - Mogul",
    img: "../../public/gomaMTubito70g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 112,
    title: "Goma Viborita - Mogul",
    img: "../../public/gomaMViborita.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 113,
    title: "Goma Osito Yummy 500g",
    img: "../../public/gomaOsitoYummy500g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 114,
    title: "Moritas gomita 30g - Yummy",
    img: "../../public/gomaYummy30g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 115,
    title: "Moritas gomitas 500g - Yummy",
    img: "../../public/gomaYummy500g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 116,
    title: "Gomita Frutal - Mogul",
    img: "../../public/gomitaMFrutal.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 117,
    title: "Gomita Frutilla 50g - Mogul",
    img: "../../public/gomitaMFrutilla50g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 118,
    title: "Gomita Acida - Mogul",
    img: "../../public/gomitaMogulAcido.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 119,
    title: "Gomita Dientecitos - Mogul",
    img: "../../public/GomitaMogulDientes.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 120,
    title: "Gomitas Frutales - Mogul",
    img: "../../public/gomitaMogulFrutales.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 121,
    title: "Gomita Tubitos - Mogul",
    img: "../../public/gomitaMogulTubitos.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 122,
    title: "Gomita Osito - Mogul",
    img: "../../public/gomitaOso.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 123,
    title: "Gomitas Piecitos ",
    img: "../../public/gomitapiecito.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 124,
    title: "Gomita Tiburon - Mogul",
    img: "../../public/gomitaTiburon.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "gomitas",
    off: false,
  },
  {
    id: 125,
    title: "Harina000 Cañuela 1kg",
    img: "../../public/HarinaCañuela000.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "harina",
    subCategoria: "",
    off: false,
  },
  {
    id: 126,
    title: "Kesitas 75g",
    img: "../../public/kesitas75g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "saladas",
    off: false,
  },
  {
    id: 127,
    title: "Kesitas 125g | caja",
    img: "../../public/kesitas125g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "saladas",
    off: false,
  },
  {
    id: 128,
    title: "Lenguetazo - Caramelo",
    img: "../../public/lenguetazo.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 129,
    title: "Madalena rellena c/DDL - Don Satur",
    img: "../../public/madaDonSaturRellDDL.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 130,
    title: "Madalena Vainilla - Don Satur",
    img: "../../public/madaDonSaturVainilla.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 131,
    title: "Malvavizco Gongys",
    img: "../../public/malvaviGongys.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "malvavizco",
    off: false,
  },
  {
    id: 132,
    title: "Malvavizco Gongys 200g",
    img: "../../public/malvaviGongys200g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "malvavizco",
    off: false,
  },
  {
    id: 133,
    title: "Malvavizco Frutilla 200g - Gongys",
    img: "../../public/malvaviGongysFrutilla200g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "malvavizco",
    off: false,
  },
  {
    id: 134,
    title: "Mantecol 26g",
    img: "../../public/mantecol26g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "Mantecol",
    off: false,
  },
  {
    id: 135,
    title: "Marroc - bocaditos",
    img: "../../public/marroc.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "chocolate",
    subCategoria: "bocados",
    off: false,
  },
  {
    id: 136,
    title: "Mentitas de Dulce de Leche",
    img: "../../public/mentitaDDL.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "mentitas",
    off: false,
  },
  {
    id: 137,
    title: "Mentita de Fruta",
    img: "../../public/mentitafrita.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "golosinas",
    subCategoria: "mentitas",
    off: false,
  },
  {
    id: 138,
    title: "MentoPlus sabor Cafe",
    img: "../../public/mentoplusCafe.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 139,
    title: "MentoPLus Cereza",
    img: "../../public/mentoplusCereza.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 140,
    title: "MentoPlus Cereza Acida",
    img: "../../public/mentoplusCerezaacida.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 141,
    title: "MentoPlus Miel",
    img: "../../public/mentoplusmiel.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 142,
    title: "MiniAlfajor Jorgito (NEGRO/BLANCO)",
    img: "../../public/minialfajorJorgito.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "alfajor",
    subCategoria: "",
    off: false,
  },
  {
    id: 143,
    title: "Bolsa Caramelo Masticable - Misky",
    img: "../../public/misky800g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "caramelo",
    subCategoria: "",
    off: false,
  },
  {
    id: 144,
    title: "Nachos Queso 70g",
    img: "../../public/nachoQueso70g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "snack",
    subCategoria: "nachos",
    off: false,
  },
  {
    id: 145,
    title: "Nachos Clasicos 110g",
    img: "../../public/nachos110g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "snack",
    subCategoria: "nachos",
    off: false,
  },
  {
    id: 146,
    title: "Rey Momo - Espuma/Nieve",
    img: "../../public/nieve.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "Nieve",
    subCategoria: "",
    off: false,
  },
  {
    id: 147,
    title: "Nutella 140g",
    img: "../../public/nutella140g.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 148,
    title: "Madalena rellena c/DDL - Don Satur",
    img: "../../public/madaDonSaturRellDDL.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 149,
    title: "Madalena rellena c/DDL - Don Satur",
    img: "../../public/madaDonSaturRellDDL.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 150,
    title: "Madalena rellena c/DDL - Don Satur",
    img: "../../public/madaDonSaturRellDDL.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
  {
    id: 151,
    title: "Madalena rellena c/DDL - Don Satur",
    img: "../../public/madaDonSaturRellDDL.jpg",
    descripcion: "",
    precioMayor: 1234,
    precioUni: 987,
    categoria: "galletitas",
    subCategoria: "dulce",
    off: false,
  },
];

export default ProductoMayor